export const ActionTypes = {
    ADD_EMPLOYEE: 'ADD_EMPLOYEE',
    SET_INIT_STATE: 'SET_INIT_STATE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
    SET_TOASTER: 'SET_TOASTER',
    SET_LOADED: 'SET_LOADED',
}